### ISSUE TITLE
Add a basic CLI version that can be executed with npx

### ISSUE THREAD

**Issue by 0xdevalias** [ehmicky/node-version-alias#10]
### Guidelines

- [X] Please search other issues to make sure this feature has not already been requested.

### Which problem is this feature request solving?

In my dotfiles I currently have the latest versions hardcoded, and need to ensure I go and manually look them up + update them each time before installing on a new machine. It would be awesome if I was able to just run this with `npx` or similar to translate the `latest` LTS/etc version automagically.

### Describe the solution you'd like

A basic CLI that can be executed with `npx` that would accept the alias as input, and output the version it correlates with.

### Pull request (optional)

- [ ] I can submit a pull request.

**Comment by ehmicky** [comment]
Hi @0xdevalias,

Thanks a lot for reaching out.

A CLI is already currently available. However, it was not documented properly, so thanks for pointing this out. I have now added a [section about CLI usage](https://github.com/ehmicky/node-version-alias#cli).

I am going to close this issue, but please let me know what you think!

@all-contributors Please add @0xdevalias for doc, question.
