### ISSUE TITLE
`lts` alias value is wrong

### ISSUE THREAD

**Issue by hongaar** [ehmicky/node-version-alias#8]
### Guidelines

- [X] Please search other issues to make sure this bug has not already been reported.
- [X] If this is related to a typo or the documentation being unclear, please click on the relevant page's `Edit` button (pencil icon) and suggest a correction instead.

### Describe the bug

Version resolver yields different results than `nvm`. When trying to resolve `lts/-1` I got back `18.12.1` but I expected `16.18.1`.

### Steps to reproduce

`node-version-alias`

```js
import nodeVersionAlias from "node-version-alias";

console.log("lts/*", await nodeVersionAlias("lts/*"));
console.log("lts/-1", await nodeVersionAlias("lts/-1"));
console.log("lts/-2", await nodeVersionAlias("lts/-2"));
```

prints

```
lts/* 18.12.1
lts/-1 18.12.1
lts/-2 16.18.1
```

vs

`nvm`

```bash
$ nvm version-remote lts/*
v18.12.1
$ nvm version-remote lts/-1
v16.18.1
$ nvm version-remote lts/-2
v14.21.1
```

### Configuration

n/a

### Environment

```
  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 5.88 GB / 7.69 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 3.3.0 - /usr/bin/yarn
    npm: 8.19.3 - ~/Code/hongaar/update-node-versions/node_modules/.bin/npm
  npmPackages:
    node-version-alias: 3.4.0 => 3.4.0
```

### Pull request (optional)

- [ ] I can submit a pull request.

**Comment by ehmicky** [comment]
Hi @hongaar,

Thanks for finding this! This has now been fixed in the latest release [`3.4.1`](https://github.com/ehmicky/node-version-alias/releases/tag/3.4.1).

@all-contributors Please add @hongaar for bug report.
